message = {'content_type': 'text', 'id': 778, 'message_id': 778,
           'from_user': {'id': 737787335, 'is_bot': False, 'first_name': 'Сергей', 'username': 'repou_xun_xona',
                         'last_name': None, 'language_code': 'ru', 'can_join_groups': None,
                         'can_read_all_group_messages': None, 'supports_inline_queries': None}, 'date': 1641288911,
           'chat': {'id': -779863901, 'type': 'group', 'title': 'test2', 'username': None, 'first_name': None,
                    'last_name': None, 'photo': None, 'bio': None, 'description': None, 'invite_link': None,
                    'pinned_message': None, 'permissions': None, 'slow_mode_delay': None,
                    'message_auto_delete_time': None, 'sticker_set_name': None, 'can_set_sticker_set': None,
                    'linked_chat_id': None, 'location': None}, 'sender_chat': None, 'forward_from': None,
           'forward_from_chat': None, 'forward_from_message_id': None, 'forward_signature': None,
           'forward_sender_name': None, 'forward_date': None, 'reply_to_message': None, 'via_bot': None,
           'edit_date': None, 'media_group_id': None, 'author_signature': None, 'text': 'sdfgdfgdf', 'entities': None,
           'caption_entities': None, 'audio': None, 'document': None, 'photo': None, 'sticker': None, 'video': None,
           'video_note': None, 'voice': None, 'caption': None, 'contact': None, 'location': None, 'venue': None,
           'animation': None, 'dice': None, 'new_chat_member': None, 'new_chat_members': None, 'left_chat_member': None,
           'new_chat_title': None, 'new_chat_photo': None, 'delete_chat_photo': None, 'group_chat_created': None,
           'supergroup_chat_created': None, 'channel_chat_created': None, 'migrate_to_chat_id': None,
           'migrate_from_chat_id': None, 'pinned_message': None, 'invoice': None, 'successful_payment': None,
           'connected_website': None, 'reply_markup': None, 'json': {'message_id': 778,
                                                                     'from': {'id': 737787335, 'is_bot': False,
                                                                              'first_name': 'Сергей',
                                                                              'username': 'repou_xun_xona',
                                                                              'language_code': 'ru'},
                                                                     'chat': {'id': -779863901, 'title': 'test2',
                                                                              'type': 'group',
                                                                              'all_members_are_administrators': True},
                                                                     'date': 1641288911, 'text': 'sdfgdfgdf'}}

print(type(message))
